### ISSUE TITLE
Test Competition Website is 404

### ISSUE THREAD

**Issue by Clearailhc** [THU-KEG/MAVEN-ERE#2]
test集合评分的网站目前关闭了，实验了一下baseline在valid集上效果会差一些，能否考虑重新上线test评测呢

**Comment by Bakser** [comment]
您好，我测试了一下，在我这里的无线网和流量中测试网站都是可以正常访问的，您可以重新访问一下，如果仍无法访问的话，可以考虑排查一下您的网络环境是否有额外的限制。
