### ISSUE TITLE
Benchmark causal F1, precision and recall on the validation set

### ISSUE THREAD

**Issue by insundaycathy** [THU-KEG/MAVEN-ERE#5]
Hi, I'm trying to a simple zero-shot method to do causal relation extraction, since there is no gold reference for the test set, I was wondering if you could provide me with a baseline F1, precision and recall performance on the validation set. 
Thank you very much

**Comment by Bakser** [comment]
Hi, thanks for your interest in our work. If you want to get the results on the test set, you can submit your predictions to CodaLab following the [instructions in README](https://github.com/THU-KEG/MAVEN-ERE#get-test-results-from-codalab). I cannot recall the exact results on the validation set. If you want reference results, you may rerun the baselines provided in this repo in your environment, which shall be more comparable to your own results.
